/**
 * Maps a WA_TEMPLATE_LANGUAGES `slug` to a representative country's ISO
 * 3166-1 alpha-2 code, for rendering a flag via flagcdn.com/w20/{code}.png.
 * Many of these languages are spoken across several countries — each entry
 * here is just one reasonable representative, not a claim of exclusivity.
 */
const LANGUAGE_FLAG_MAP: Record<string, string> = {
  af: "za",
  sq: "al",
  ar: "sa",
  az: "az",
  bn: "bd",
  bg: "bg",
  ca: "es",
  zh_CN: "cn",
  zh_HK: "hk",
  zh_TW: "tw",
  hr: "hr",
  cs: "cz",
  da: "dk",
  nl: "nl",
  en: "us",
  en_GB: "gb",
  en_US: "us",
  et: "ee",
  fil: "ph",
  fi: "fi",
  fr: "fr",
  ka: "ge",
  de: "de",
  el: "gr",
  gu: "in",
  ha: "ng",
  he: "il",
  hi: "in",
  hu: "hu",
  id: "id",
  ga: "ie",
  it: "it",
  ja: "jp",
  kn: "in",
  kk: "kz",
  rw_RW: "rw",
  ko: "kr",
  ky_KG: "kg",
  lo: "la",
  lv: "lv",
  lt: "lt",
  mk: "mk",
  ms: "my",
  ml: "in",
  mr: "in",
  nb: "no",
  fa: "ir",
  pl: "pl",
  pt_BR: "br",
  pt_PT: "pt",
  pa: "in",
  ro: "ro",
  ru: "ru",
  sr: "rs",
  sk: "sk",
  sl: "si",
  es: "es",
  es_AR: "ar",
  es_ES: "es",
  es_MX: "mx",
  sw: "tz",
  sv: "se",
  ta: "in",
  te: "in",
  th: "th",
  tr: "tr",
  uk: "ua",
  ur: "pk",
  uz: "uz",
  vi: "vn",
  zu: "za",
};

export function getLanguageFlag(slug: string): string | null {
  return LANGUAGE_FLAG_MAP[slug] ?? null;
}
